-- Schema is created automatically by TypeORM (synchronize: true) the
-- first time the Nest app starts, so this file no longer defines tables
-- directly. See src/entities/ for the actual schema (auth_event,
-- issuance_session, verification_session).
-- Left in place / still mounted by docker-compose.yml in case extensions
-- or seed data are needed here later.
